// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_profile.proto

package user_profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseHeader struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49b5b3a45c8a339, []int{0}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseHeader) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ChoseRequest struct {
	UserId               uint32            `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Features             []string          `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	Ext                  map[string]string `protobuf:"bytes,16,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChoseRequest) Reset()         { *m = ChoseRequest{} }
func (m *ChoseRequest) String() string { return proto.CompactTextString(m) }
func (*ChoseRequest) ProtoMessage()    {}
func (*ChoseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49b5b3a45c8a339, []int{1}
}

func (m *ChoseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChoseRequest.Unmarshal(m, b)
}
func (m *ChoseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChoseRequest.Marshal(b, m, deterministic)
}
func (m *ChoseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChoseRequest.Merge(m, src)
}
func (m *ChoseRequest) XXX_Size() int {
	return xxx_messageInfo_ChoseRequest.Size(m)
}
func (m *ChoseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChoseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChoseRequest proto.InternalMessageInfo

func (m *ChoseRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChoseRequest) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *ChoseRequest) GetExt() map[string]string {
	if m != nil {
		return m.Ext
	}
	return nil
}

type ChoseResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChoseResponse) Reset()         { *m = ChoseResponse{} }
func (m *ChoseResponse) String() string { return proto.CompactTextString(m) }
func (*ChoseResponse) ProtoMessage()    {}
func (*ChoseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49b5b3a45c8a339, []int{2}
}

func (m *ChoseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChoseResponse.Unmarshal(m, b)
}
func (m *ChoseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChoseResponse.Marshal(b, m, deterministic)
}
func (m *ChoseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChoseResponse.Merge(m, src)
}
func (m *ChoseResponse) XXX_Size() int {
	return xxx_messageInfo_ChoseResponse.Size(m)
}
func (m *ChoseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChoseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChoseResponse proto.InternalMessageInfo

func (m *ChoseResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseHeader)(nil), "user_profile.ResponseHeader")
	proto.RegisterType((*ChoseRequest)(nil), "user_profile.ChoseRequest")
	proto.RegisterMapType((map[string]string)(nil), "user_profile.ChoseRequest.ExtEntry")
	proto.RegisterType((*ChoseResponse)(nil), "user_profile.ChoseResponse")
}

func init() { proto.RegisterFile("user_profile.proto", fileDescriptor_b49b5b3a45c8a339) }

var fileDescriptor_b49b5b3a45c8a339 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x03, 0xdb, 0x52, 0x98, 0xb6, 0x86, 0x4c, 0x4c, 0x24, 0xe8, 0x81, 0xe0, 0x85, 0x13,
	0x07, 0xd4, 0xc6, 0x78, 0x32, 0x31, 0x18, 0xff, 0xdc, 0xf6, 0x0b, 0x18, 0x94, 0x69, 0xda, 0xd8,
	0x74, 0x71, 0x77, 0x31, 0xed, 0x37, 0xf3, 0xe3, 0x99, 0x5d, 0xd0, 0x94, 0x44, 0x6f, 0xf3, 0x1e,
	0xc3, 0x6f, 0xdf, 0xdb, 0x05, 0x6c, 0x15, 0xc9, 0x97, 0x46, 0x8a, 0xe5, 0x7a, 0x43, 0x79, 0x23,
	0x85, 0x16, 0x38, 0x3b, 0xf4, 0xd2, 0x05, 0x1c, 0x71, 0x52, 0x8d, 0xd8, 0x2a, 0x7a, 0xa0, 0xaa,
	0x26, 0x89, 0x08, 0xa3, 0x37, 0x51, 0x53, 0xe4, 0x24, 0x4e, 0x36, 0xe7, 0x76, 0xc6, 0x10, 0x18,
	0x49, 0x19, 0xb1, 0xc4, 0xc9, 0x02, 0x6e, 0xc6, 0xf4, 0xcb, 0x81, 0xd9, 0xdd, 0x4a, 0x28, 0xe2,
	0xf4, 0xd1, 0x92, 0xd2, 0x78, 0x02, 0x13, 0x0b, 0x5e, 0xd7, 0xfd, 0x9f, 0x9e, 0x91, 0x8f, 0x35,
	0xc6, 0xe0, 0x2f, 0xa9, 0xd2, 0xad, 0x24, 0x15, 0xb9, 0x09, 0xcb, 0x02, 0xfe, 0xab, 0xf1, 0x0a,
	0x18, 0xed, 0x74, 0x14, 0x26, 0x2c, 0x9b, 0x16, 0xe7, 0xf9, 0x20, 0xed, 0x21, 0x3d, 0x2f, 0x77,
	0xba, 0xdc, 0x6a, 0xb9, 0xe7, 0x66, 0x3f, 0x5e, 0x80, 0xff, 0x63, 0x98, 0x68, 0xef, 0xb4, 0xb7,
	0x67, 0x06, 0xdc, 0x8c, 0x78, 0x0c, 0xe3, 0xcf, 0x6a, 0xd3, 0x52, 0xe4, 0x5a, 0xaf, 0x13, 0x37,
	0xee, 0xb5, 0xf3, 0x34, 0xf2, 0x59, 0x18, 0xa6, 0x25, 0xcc, 0x7b, 0x76, 0xd7, 0x1b, 0x2f, 0xc1,
	0x5b, 0xd9, 0xee, 0x96, 0x32, 0x2d, 0xce, 0x86, 0x41, 0x86, 0xf7, 0xc3, 0xfb, 0xdd, 0xe2, 0x19,
	0x26, 0xf7, 0x5d, 0x0f, 0xbc, 0x85, 0xb1, 0x25, 0x62, 0xfc, 0x7f, 0x85, 0xf8, 0xf4, 0xcf, 0x6f,
	0x1d, 0xfa, 0xd5, 0xb3, 0x6f, 0x73, 0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x21, 0xba, 0x52, 0x77,
	0xb1, 0x01, 0x00, 0x00,
}
